### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([57, 99, 96, 55, 89, 12, 49, 41, 86, 21, 19,  5, 47, 17, 81])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[72, 90, 80, 59],
       [68, 94, 12, 82],
       [ 9, 89, 25, 35],
       [98, 50, 84, 82],
       [11, 29,  2, 26],
       [76, 34, 39, 92]])

In [4]:
np.sort(a)[::-1]

array([99, 96, 89, 86, 81, 57, 55, 49, 47, 41, 21, 19, 17, 12,  5])

In [8]:
np.sort(b,axis=1)
#0 for row sort
# 1 for column sort

array([[59, 72, 80, 90],
       [12, 68, 82, 94],
       [ 9, 25, 35, 89],
       [50, 82, 84, 98],
       [ 2, 11, 26, 29],
       [34, 39, 76, 92]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
# code
np.append(a,200)

array([ 57,  99,  96,  55,  89,  12,  49,  41,  86,  21,  19,   5,  47,
        17,  81, 200])

In [10]:
b

array([[72, 90, 80, 59],
       [68, 94, 12, 82],
       [ 9, 89, 25, 35],
       [98, 50, 84, 82],
       [11, 29,  2, 26],
       [76, 34, 39, 92]])

In [11]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[72.        , 90.        , 80.        , 59.        ,  0.73858484],
       [68.        , 94.        , 12.        , 82.        ,  0.57473737],
       [ 9.        , 89.        , 25.        , 35.        ,  0.23992441],
       [98.        , 50.        , 84.        , 82.        ,  0.16765066],
       [11.        , 29.        ,  2.        , 26.        ,  0.90548249],
       [76.        , 34.        , 39.        , 92.        ,  0.65562303]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [12]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [15]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [16]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [17]:
# code
a.shape

(15,)

In [18]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [19]:
np.expand_dims(a,axis=1)

array([[57],
       [99],
       [96],
       [55],
       [89],
       [12],
       [49],
       [41],
       [86],
       [21],
       [19],
       [ 5],
       [47],
       [17],
       [81]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [20]:
a

array([57, 99, 96, 55, 89, 12, 49, 41, 86, 21, 19,  5, 47, 17, 81])

In [21]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  3,  4,  8, 14]),)

In [22]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  0,  0,  0, 12, 49, 41,  0, 21, 19,  5, 47, 17,  0])

In [23]:
np.where(a%2 == 0,0,a)

array([57, 99,  0, 55, 89,  0, 49, 41,  0, 21, 19,  5, 47, 17, 81])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [24]:
# code
a

array([57, 99, 96, 55, 89, 12, 49, 41, 86, 21, 19,  5, 47, 17, 81])

In [25]:
np.argmax(a)

np.int64(1)

In [26]:
b

array([[72, 90, 80, 59],
       [68, 94, 12, 82],
       [ 9, 89, 25, 35],
       [98, 50, 84, 82],
       [11, 29,  2, 26],
       [76, 34, 39, 92]])

In [27]:
np.argmax(b,axis=0)

array([3, 1, 3, 5])

In [28]:
np.argmax(b,axis=1)

array([1, 1, 1, 0, 1, 3])

In [29]:
# np.argmin
np.argmin(a)

np.int64(11)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [30]:
a

array([57, 99, 96, 55, 89, 12, 49, 41, 86, 21, 19,  5, 47, 17, 81])

In [31]:
np.cumsum(a)

array([ 57, 156, 252, 307, 396, 408, 457, 498, 584, 605, 624, 629, 676,
       693, 774])

In [32]:
b

array([[72, 90, 80, 59],
       [68, 94, 12, 82],
       [ 9, 89, 25, 35],
       [98, 50, 84, 82],
       [11, 29,  2, 26],
       [76, 34, 39, 92]])

In [33]:
np.cumsum(b,axis=1)

array([[ 72, 162, 242, 301],
       [ 68, 162, 174, 256],
       [  9,  98, 123, 158],
       [ 98, 148, 232, 314],
       [ 11,  40,  42,  68],
       [ 76, 110, 149, 241]])

In [34]:
np.cumsum(b)

array([  72,  162,  242,  301,  369,  463,  475,  557,  566,  655,  680,
        715,  813,  863,  947, 1029, 1040, 1069, 1071, 1097, 1173, 1207,
       1246, 1338])

In [35]:
# np.cumprod
np.cumprod(a)

array([                  57,                 5643,               541728,
                   29795040,           2651758560,          31821102720,
              1559234033280,       63928595364480,     5497859201345280,
         115455043228250880,  2193645821336766720, -7478514967025718016,
       -1002066049727266048,  1411621228346028800,  3660855053771023104])

In [36]:
a

array([57, 99, 96, 55, 89, 12, 49, 41, 86, 21, 19,  5, 47, 17, 81])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [37]:
a

array([57, 99, 96, 55, 89, 12, 49, 41, 86, 21, 19,  5, 47, 17, 81])

In [38]:
np.percentile(a,50)

np.float64(49.0)

In [39]:
np.median(a)

np.float64(49.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [40]:
# code
a

array([57, 99, 96, 55, 89, 12, 49, 41, 86, 21, 19,  5, 47, 17, 81])

In [46]:
bin=np.arange(10,100,10)
np.histogram(a,bins=bin)
# bin|

(array([3, 1, 0, 3, 2, 0, 0, 3]), array([10, 20, 30, 40, 50, 60, 70, 80, 90]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [48]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [49]:
# code
a


array([57, 99, 96, 55, 89, 12, 49, 41, 86, 21, 19,  5, 47, 17, 81])

In [50]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([], dtype=int64)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [51]:
# code
a

array([57, 99, 96, 55, 89, 12, 49, 41, 86, 21, 19,  5, 47, 17, 81])

In [52]:
np.flip(a)

array([81, 17, 47,  5, 19, 21, 86, 41, 49, 12, 89, 55, 96, 99, 57])

In [53]:
b

array([[72, 90, 80, 59],
       [68, 94, 12, 82],
       [ 9, 89, 25, 35],
       [98, 50, 84, 82],
       [11, 29,  2, 26],
       [76, 34, 39, 92]])

In [54]:
np.flip(b,axis=1)

array([[59, 80, 90, 72],
       [82, 12, 94, 68],
       [35, 25, 89,  9],
       [82, 84, 50, 98],
       [26,  2, 29, 11],
       [92, 39, 34, 76]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [55]:
# code
a

array([57, 99, 96, 55, 89, 12, 49, 41, 86, 21, 19,  5, 47, 17, 81])

In [ ]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.delete(a,[0,2,4])

array([530,  50,  37,  94,  92,   5,  30,  68,   9,  78,   2,  21])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals

In [34]:
import numpy as np

arr = np.random.random((200))
arr=np.round(arr,3)
np.percentile(arr,51)-np.percentile(arr,50)

np.float64(0.01146999999999998)